In [30]:
import pandas as pd
from datetime import datetime, date, timedelta

In [31]:
df = pd.read_excel('../clients/sinpoong_swing/high_records.xlsx')

In [32]:
df

,Unnamed: 0,code,date,name,was_all_high,open,high,close,low,high_time_sec,low_time_sec,high_time,low_time,volatability
0,0,A051490,20200923,나라엠앤디,False,12.50,16.67,-10.00,-12.50,120,22500,905,1518,29.17
1,1,A054180,20200923,메디콕스,False,13.02,23.08,6.51,1.38,3780,1560,1006,929,21.70
2,2,A122690,20200923,서진오토모티브,False,4.29,16.98,-5.41,-9.51,480,20760,909,1447,26.49
3,3,A182690,20200923,테라셈,False,8.47,29.83,8.14,2.71,4140,19140,1012,1422,27.12
4,4,A239340,20200923,줌인터넷,False,4.41,29.89,29.89,4.19,19680,0,1429,901,25.70
5,5,A241820,20200923,피씨엘,False,0.57,28.06,10.68,-3.56,21960,300,1507,906,31.62
6,6,A267320,20200923,나인테크,False,8.34,18.96,-9.32,-10.62,480,22680,909,1519,29.58
7,7,A006110,20200923,삼아알미늄,False,1.42,4.27,-12.04,-15.07,840,21960,915,1507,19.34

In [12]:
df.describe()

,Unnamed: 0,open,high,close,low,high_time,low_time,volatability
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,252.500000,7.647055,17.938913,3.744249,-2.868538,964.796443,1229.924901,20.807451
std,146.213884,9.455214,10.537775,14.508822,11.331213,221.689302,324.601212,9.408725
min,0.000000,-20.020000,-9.040000,-29.070000,-29.980000,0.000000,0.000000,0.000000
25%,126.250000,0.832500,9.515000,-6.750000,-10.100000,903.000000,924.750000,15.637500
50%,252.500000,6.650000,19.675000,0.490000,-4.615000,912.000000,1349.000000,20.375000
75%,378.750000,12.442500,28.915000,11.615000,1.970000,1001.000000,1511.750000,26.290000
max,505.000000,30.000000,30.000000,30.000000,30.000000,1520.000000,1530.000000,54.270000

In [19]:
df['low_time'] = df['low_time'].apply(lambda x: datetime(2020, 9, 23, int(x / 100), int(x % 100)))
df['high_time'] = df['high_time'].apply(lambda x: datetime(2020, 9, 23, int(x / 100), int(x % 100)))

In [20]:
df.describe()

,Unnamed: 0,open,high,close,low,volatability
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,252.500000,7.647055,17.938913,3.744249,-2.868538,20.807451
std,146.213884,9.455214,10.537775,14.508822,11.331213,9.408725
min,0.000000,-20.020000,-9.040000,-29.070000,-29.980000,0.000000
25%,126.250000,0.832500,9.515000,-6.750000,-10.100000,15.637500
50%,252.500000,6.650000,19.675000,0.490000,-4.615000,20.375000
75%,378.750000,12.442500,28.915000,11.615000,1.970000,26.290000
max,505.000000,30.000000,30.000000,30.000000,30.000000,54.270000

In [26]:
times = pd.DatetimeIndex(df.low_time)
groupd = df.groupby([times.hour])

In [29]:
for k, v in groupd:
    print(type(groupd.get_group(k)))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [25]:
times

DatetimeIndex(['2020-09-23 15:18:00', '2020-09-23 09:29:00',
               '2020-09-23 14:47:00', '2020-09-23 14:22:00',
               '2020-09-23 09:01:00', '2020-09-23 09:06:00',
               '2020-09-23 15:19:00', '2020-09-23 15:07:00',
               '2020-09-23 09:09:00', '2020-09-23 09:14:00',
               ...
               '2020-09-23 10:49:00', '2020-09-23 09:09:00',
               '2020-09-23 10:45:00', '2020-09-23 13:44:00',
               '2020-09-23 14:24:00', '2020-09-23 09:01:00',
               '2020-09-23 09:07:00', '2020-09-23 10:19:00',
               '2020-09-23 10:27:00', '2020-09-23 09:31:00'],
              dtype='datetime64[ns]', name='low_time', length=506, freq=None)